### ISSUE TITLE
HTML options.

### ISSUE THREAD

**Issue by mediatainment** [jim/carmen#109]
Is there a way to pass html_options like

    f.country_select(:country_code, priority: %w(US CA), prompt: 'Please select a country', { :class => 'my_style_class' })

or like rails use select fields

    f.country_select(:country_code, priority: %w(US CA), prompt: 'Please select a country', {}, { :class => 'my_style_class' })

I try to style my country_select for twitter bootstrap (eg: span2 class for a smaller version)

thanks for your response. :-)

**Comment by CDainMiller** [comment]
Should this be an issue in rails-carmen? Not sure it makes sense for this repo? Also very old, closing for now.
