### ISSUE TITLE
Appended data paths require files for all regions to be present

### ISSUE THREAD

**Issue by tylerhunt** [jim/carmen#114]
The comment for `Carmen::Region#load_data_at_path` says:

> The resulting data will be the result of loading the file from the data_path and overlaying matching data (if it exists) from the overlay_path.

According to this, the path should not be loaded unless it exists, but this isn't currently happening.

I've done this:

``` ruby
Carmen.append_data_path Rails.root.join('config')
```

And added files at `config/world.yml` and `config/world/us.yml`, which works fine for the US, but now when fetching the subregions for other countries, I get an error like this:

    Errno::ENOENT: No such file or directory - /app/config/world/gb.yml

Additionally, I don't actually need a `world.yml` file in this case, but without it I get:

    Errno::ENOENT: No such file or directory - /app/config/world.yml

**Comment by CDainMiller** [comment]
@tylerhunt @DarkFox Could anyone confirm this was actually fixed? I can setup a test if not :)

**Comment by tylerhunt** [comment]
I don't have still have an app using this to test the fix. After poking around with it in a test script, it does appear to be working, though.
