### ISSUE TITLE
_enabled value not working for subregions

### ISSUE THREAD

**Issue by DarkFox** [jim/carmen#119]
We need to replace the values of the Chinese subregions (and remove one), for compatibility with another system (two-letter codes instead of numbers), however, just adding the cn.yml file with our own values as per the README, only adds them to the list.

However, adding the regions with the original numbers and putting _enabled: false on each, doesn't fix it.

**Comment by jim** [comment]
Closing this for now. Please reopen with YAML examples if it is still an issue.
