### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by saibharathkumar** [jim/carmen#143]
Hello,
can u please help me , how can I have the state (or) country names without any special characters and only in English Language.
for eg: Carmen::Country.named("Sri Lanka").subregions.collect{|p| p.name} will give an array of state names with spl characters.

**Comment by CDainMiller** [comment]
We are merging this conversation into our version 2.0 ticket. We'll reference this issue there, but any ongoing conversation can be had on that thread. Sorry for the year-later reply!
