### ISSUE TITLE
Use of carmen to initialize class constants failing

### ISSUE THREAD

**Issue by adailey14** [jim/carmen#145]
I am not 100% sure this is an issue with Carmen, it may be an issue with how i have configured my rails application. But I will describe it here nonetheless:

I am using Carmen to initialize some class constants like so (concocted example):

```ruby
require 'carmen'
class StateHolder{
  include Carmen
  STATE_CODES = Carmen::Country.named("United States").subregions.map{|sr| sr.code}
  ...
end
```

This will give an error message that Country.named("United States") is nil.

I find that if I run Carmen.reset_i18n_backend as part of the Constant assignment, things work smoothly.

It appears self.reset_i18n_backend is being called from within the Carmen Module declaration in carmen.rb. For whatever reason, Rails initialization is setup so that code is not being called before I initialize my class constant. Perhaps that code should be called within the carmen class declaration rather than as part of the Carmen module declaration so Carmen functionality will be easily available within Constant initializations like in my case.

**Comment by jim** [comment]
It's probably that under Rails we use its i18n backend, but that means we're dependent on it for lookups by name. If you're still having an issue, please post an issue to [carmen-rails](https://github.com/jim/carmen-rails).

In general, Carmen tries to lazily load data, so it's behavior before and during application initialization is a bit undefined.
