### ISSUE TITLE
Subregions: undefined method 'named' for Array: []

### ISSUE THREAD

**Issue by nathany** [jim/carmen#155]
I have some code like this:

```ruby
subregion = Carmen::Country.named(name).subregions.named(str)
if sub_region
  # do stuff
end
```

But it is currently failing sometimes because `load_regions` returns an empty array when there are no regions, rather than an empty RegionCollection.

See https://github.com/jim/carmen/blob/master/lib/carmen/region.rb#L68

**Comment by CDainMiller** [comment]
Thanks for the suggestion nathany, we might actually want to add that RegionCollection. This looks like something we might want for v2, so I'm gonna close this thread and reference it in our new issue.
