### ISSUE TITLE
Query for a region by name or code

### ISSUE THREAD

**Issue by sergey-alekseev** [jim/carmen#156]
Currently Carmen allows to query for a country by name or code:
```ruby
us = Country.named('United States')
```
(like README says https://github.com/jim/carmen#how-to-use-carmen).

However why doesn't Carmen allow to query for a region by name or code?
Like the following:
```ruby
minsk = Region.named('Horad Minsk')
# or
minsk = RegionCollection.named('Horad Minsk')
```

**Comment by CDainMiller** [comment]
Adding to our v2 branch for consideration into the v2 backlog! Thanks @sergey-alekseev
