### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by jim** [jim/carmen#169]
It's probably worth pushing a new release with various fixes (such as #161) sometime soon.

**Comment by CDainMiller** [comment]
Agreed. I can get one out very soon.

**Comment by CDainMiller** [comment]
Released v1.0.2 with all current changes on master. https://rubygems.org/gems/carmen

**Comment by jim** [comment]
Thanks!

**Comment by CDainMiller** [comment]
Np! :+1:
