### ISSUE TITLE
New Ireland postal codes

### ISSUE THREAD

**Issue by jtapia** [jim/carmen#172]
Hey guys, Are you aware of this http://en.wikipedia.org/wiki/Postal_addresses_in_the_Republic_of_Ireland?

**Comment by CDainMiller** [comment]
I was not! Thanks for the reference!

**Comment by CDainMiller** [comment]
I'm going to close this for now though, but let's deff open another one if we implement them. I think we also have some ongoing postal code conversation in other issues & PRs as well :)
