### ISSUE TITLE
Translation of subregions (for non English locales)

### ISSUE THREAD

**Issue by xandrck** [jim/carmen#198]
Hi guys, I wanna to ask about translation of subregions, I tried to find it, but I found nothing.
I'm interesting in RU subregions translation, Is it exist?

**Comment by ecbypi** [comment]
The following wiki page goes over how to update translations.  https://github.com/jim/carmen/wiki/Contributing-Data

Let me know if you have any questions beyond that.

**Comment by xandrck** [comment]
Yes, I saw that, thanks.
I was talking about carmen project resources and I'm asking about next:
for example I have RU locale (setting it by `Carmen.i18n_backend.locale = :ru`)
so when I execute next code `Carmen::Country.coded('RU').subregions` I expect it to return subregions with translated names, but I get all of them on english.

As I see [here](https://github.com/jim/carmen/blob/master/locale/overlay/ru/world/ru.yml) the subregions are translated, how can I used this translation?

p.s. `Carmen::Country.coded('RU')` return translated country (on russian), so locale is set.

Thanks

**Comment by jcsrb** [comment]
@xandrck be sure to fetch master from github not `1.0.2` from rubygems, as `1.0.2` doesn't have all the translations merged yet 

![image](https://cloud.githubusercontent.com/assets/119011/13479933/2296eef2-e0e3-11e5-8c5f-da5b5a78a40f.png)

**Comment by xandrck** [comment]
@jcsrb thanks, that's what I'm looking for :+1:

**Comment by parimaay** [comment]
Hello,

I'm facing the same issue of translations of subregions but for the Simplified Chinese with `gem "carmen", "~> 1.1.3"`
I have done as following but am still getting the English translation for subregions:

``` Ruby
Carmen.i18n_backend.locale = :cn
Carmen::Country.coded('CN').subregions
```
![Screen Shot 2021-08-11 at 10 32 46 AM](https://user-images.githubusercontent.com/25180511/129048521-e64bafeb-ef01-4ac1-88f7-10a2ef638a5c.png)
