### ISSUE TITLE
converting country to json leads to deep recursion

### ISSUE THREAD

**Issue by zarelit** [jim/carmen#209]
When using Carmen in Rails, converting a Country to JSON results in a `SystemStackError: stack level too deep` error.

Steps to reproduce:
1. open rails console
2. `us = Carmen::Country.named('United States')`
3. `us.to_json`

**Comment by dainmiller** [comment]
I was able to reproduce. Thanks for reporting. This shouldn't be too hard to fix!

**Comment by ricas07** [comment]
Is there a solution to this? How do I return a json object including country and subregions?
