### ISSUE TITLE
Undefined methods and nil results

### ISSUE THREAD

**Issue by nonadmin** [jim/carmen#211]
Been pulling my hair out with this one.  I'm getting a lot of undefined methods or nil results when using some of the query examples from the readme.

For instance
```
2.3.0 :003 > ad = Country.numeric_coded('020')
NoMethodError: undefined method `numeric_coded' for Carmen::Country:Class
```

Also
```
2.3.0 :007 > us = Country.coded('840')
 => nil
```

Any idea whats going on here?  What's bizarre is that I cloned the gem and ran the tests and of course they all pass using very similar methods.  Using Ruby 2.3.0 here.

**Comment by nonadmin** [comment]
I think there's a version discrepancy between the git repo and rubygems?  If I source directly from github in my Gemfile, the same methods work just fine.

**Comment by ecbypi** [comment]
What's on GitHub and what's published on rubygems aren't guaranteed to be identical.  To see what's on rubygems, view the project from the matching tag:

https://github.com/jim/carmen/tree/v1.0.2
