### ISSUE TITLE
Country aliases/synonyms ("Vietnam" for "Viet Nam")?

### ISSUE THREAD

**Issue by TylerRick** [jim/carmen#54]
Sometimes a country is commonly referred to by names *other* than the name officially assigned by ISO 3166.

This presents a problem when you are trying to automatically interpret user-supplied data as I am trying to do. Users don't know or care which name ISO 3166 deems "official" -- they may have other ideas about the correct name for a country.

Case in point: **Vietnam**. ISO 3166 seems to have assigned it the name "**Viet Nam**" but I think it is more commonly known as "**[Vietnam](http://en.wikipedia.org/wiki/Vietnam)**". Even with the regular expression searching currently done by `Carmen::country_code`, the lookup fails for this case:

```
irb -> Carmen::country_code('Vietnam')
    => nil
```

&mdash; which of course surprised me, that it wouldn't recognize this well-known country name.

I've worked around this problem in my *own* code by creating a very simple country synonym checking method, but I'm hoping that *official* support for aliases/synonyms could be added (or some other solution that solves this problem :))...

Interesting to note:

* Wikipedia refers to it as **Vietnam** here: http://en.wikipedia.org/wiki/ISO_3166-2:VN
* But as **Viet Nam** here: http://en.wikipedia.org/wiki/Template:ISO_3166_code_Viet_Nam
* As a possible enhancement, they have [this similar idea on their list](http://en.wikipedia.org/wiki/Template:ISO_3166_name): "**Adding country synonyms**: these should redirect to the canonical template...", so I know I'm not the first to have thought of this idea...

**Comment by CDainMiller** [comment]
Closing here, but referencing in our v2 ticket. Aliasing in general is definitely something we are thinking about!

**Comment by chriddyp** [comment]
Just curious, did you folks find a solution looking up country synonyms/aliases (e.g. USA, US, America, United States, United States of America)? A project I'm working on has a similar problem and this thread came up on a google search.

**Comment by CDainMiller** [comment]
@chriddyp It's something we are still working on implementing, but I think we agreed on a tentative solution if I remember correctly. We would love a PR though if you have any ideas or if you implement something on your existing project and want to backport it into a Carmen PR. :)

**Comment by chriddyp** [comment]
@CDainMiller looks like we'll probably start with the regexes maintained in this module: https://github.com/vincentarelbundock/countrycode/blob/master/data/countrycode_data.csv

**Comment by CDainMiller** [comment]
@chriddyp Fantastic, thanks for the heads up.

**Comment by modullar** [comment]
Look up country by name is required.
```
pry(main)> Carmen::Country.named("The Bahamas")
=> nil
pry(main)> Carmen::Country.named("USA")
=> nil
```

**Comment by StanisLove** [comment]
I've overcome it like this
- Added a new key to locales
```yml
ru:
  world:
    by:
      common_name: !!null
      name: Беларусь
      name_aliases:
        - Белорусь
        - Белорус
        - Белоруссия
        - Белорусия
        - Беларус
        - Беларуссия
        - Беларусия
      official_name: Республика Беларусь
```
- Loaded custom locales in initializer
```ruby
  Carmen.i18n_backend.append_locale_path(Rails.root.join("config", "locales", "countries"))
```
- Added a method to `Carmen::Country`
```ruby
  Carmen::Country.class_eval do
    def name_aliases
      Array.wrap(
        Carmen.i18n_backend.translate(path("name_aliases"))
      ) + [name, official_name].compact
    end
```
`Carmen::Country#path` is a public method so you don't have to use Monkey patching
