### ISSUE TITLE
Names of states for India are incorrect

### ISSUE THREAD

**Issue by bikramwp** [jim/carmen#77]
I'm not sure where the state names for India came from, but the typical and common English names used in all correspondence (addresses, government documents, etc.) do not use names like Himāchal Pradesh, Mahārāshtra or Damān and Diu (note the accented ā characters). The name in such cases use the "normal" non-accented characters such as in Himachal Pradesh, Maharashtra and Daman and Diu.

Ps. The Wikipedia article at http://en.wikipedia.org/wiki/States_and_territories_of_India contains the correct names as of today.

Ps. I am referring to the list of states in the `iso_data/world/in.yml` file.

**Comment by CDainMiller** [comment]
Very old issue at this point. We are using data that is from a reputable third party and also I don't know enough about accented characters to say one or the other. If you guys still think this is a worthwhile change lets open another issue on it.
